### ISSUE TITLE
any client that in this repo and have this hud style?

### ISSUE THREAD

**Issue by pp0236** [chocopie69/Minecraft-Modifications-Codes#5]
![hJi8ZbTBDR](https://user-images.githubusercontent.com/54238880/150290204-ccf093e1-dd03-43b0-a25a-3df4948b7f08.png)

**Comment by hard-shutdown** [comment]
I think astro client has a toggleable option like that, compile it and try it out.

**Comment by pp0236** [comment]
> I think astro client has a toggleable option like that, compile it and try it out.

ty for telling, the code work just fine
![javaw_gWxktOjrKi](https://user-images.githubusercontent.com/54238880/152966064-f06498e8-f7c6-40e3-98f3-c95892223cbc.gif)
